import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import Providers from '../redux/Provider'

export const metadata = {
  title: 'BBTS',
  description: 'Generated by Next.js',
  icons: {
    icon: '/BancoDoBrasil-Logo.svg',
  },
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.className} overflow-hidden`}>
      <body className='bg-white text-black'>
        <Providers>
          <div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
