import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import Providers from '../redux/Provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>
          <div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
